name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

env:
  AWS_DEFAULT_REGION: us-east-1
  IMAGE_REPO_NAME: my-app
  IMAGE_TAG: latest
  CLUSTER_NAME: my-eks-cluster
  SERVICE_NAME: my-app-service
  DEPLOYMENT_NAME: my-app-deployment
  DOCKERHUB_USERNAME_ID: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN_KEY: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - # login to Docker Hub using the secrets provided
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME_ID }}
          password: ${{ env.DOCKERHUB_TOKEN_KEY }}
        
      - # create a buildkit builder instance
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    
      - # build the container image and push it to Docker Hub with the name clockbox.
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME_ID }}/clockbox:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - # create a buildkit builder instance
        name: Create Amazon EKS cluster
        uses: aws-actions/amazon-eks-create-cluster@v1
        with:
          name: ${{ env.CLUSTER_NAME }}
          version: 1.21
          subnets: |
            subnet-01
            subnet-02
          security-group: sg-01
          tags: |
            key1=value1
            key2=value2
        id: create-cluster
      - # create a buildkit builder instance
        name: Configure kubectl
        uses: steebchen/kubectl@v1
        with:
          version: '1.21.3'
