name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

env:
  AWS_DEFAULT_REGION: us-east-1
  IMAGE_REPO_NAME: my-app
  IMAGE_TAG: latest
  CLUSTER_NAME: my-eks-cluster
  SERVICE_NAME: my-app-service
  DEPLOYMENT_NAME: my-app-deployment
  DOCKERHUB_USERNAME_ID: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN_KEY: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - # login to Docker Hub using the secrets provided
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME_ID }}
          password: ${{ env.DOCKERHUB_TOKEN_KEY }}
        
      - # create a buildkit builder instance
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    
      - # build the container image and push it to Docker Hub with the name clockbox.
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME_ID }}/clockbox:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - # Install kubectl
        name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
          echo "$(<kubectl.sha256) kubectl" | sha256sum --check

          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client

      - # Configure AWS Credentials
        name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - # kube config
        name: Update kube config
        run: aws eks update-kubeconfig --name eks_test --region us-west-1
    
